School_Project/School_App/urls.py
from django.urls import path, include
from School_App import views

app_name='School_App'
urlpatterns = [
    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('enroll',views.enroll,name='enroll'),
    path('add/',views.StudentCreateView.as_view(),name='student_add'),
    path('ajax/load-course',views.load_courses,name='ajax_load_courses'),
    ]

School_Project/School_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('School_App.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

School_Project/School_App/models.py
from django.db import models
from datetime import datetime

GENDER_CHOICES = [('Male','Male'),('Female','Female')]
# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name
    
class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name
    
class Purpose(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return self.name
    
class Student(models.Model):
    name = models.CharField(max_length=100)
    dob=models.DateField(auto_now=False, auto_now_add=False)
    age=models.IntegerField()
    gender=models.CharField(max_length=10,
                            choices= GENDER_CHOICES)
    phone = models.IntegerField()
    mail = models.EmailField(unique=True)
    address = models.TextField(max_length=700)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    purpose = models.ForeignKey(Purpose, on_delete=models.SET_NULL, blank=True, null=True)
    materials_provided = models.CharField(max_length=150, null=True)

    def __str__(self) -> str:
        return self.name
    

School_Project/School_App/forms.py
from django import forms
from . models import Student, Course

GENDER_CHOICES = [('Male','Male'),('Female','Female')]
MATERIAL_CHOICE = [
    ('Note Books','Note books'),
    ('Academic Books','Academic Books'),
    ('Stationery Supplies','Stationery Supplies'),
    ('Uniform','Uniform'),
    ('Lab Utilities','Lab Utilities')

]
class StudentForm(forms.ModelForm):
    gender = forms.ChoiceField(choices= GENDER_CHOICES,widget=forms.RadioSelect)
    materials_provided = forms.MultipleChoiceField(label='Materials Provided', choices=MATERIAL_CHOICE, widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Student
        fields = ('name','dob','age','gender','phone','mail','address','department','course','purpose','materials_provided')
        labels = {'name':'Name','dob':'Date Of Birth','age':'Age','gender':'Gender','phone':'Phone Number','mail':'Email ID','address':'Address','department':'Department','course':'Course','purpose':'Purpose','materials_provided':'Materials Provided'}
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'dob':forms.DateInput(attrs={'class':'form-control', 'id':'datepicker'}),
            'age':forms.NumberInput(attrs={'class':'form-control'}),
            'phone':forms.NumberInput(attrs={'class':'form-control'}),
            'mail':forms.EmailInput(attrs={'class':'form-control'}),
            'address':forms.Textarea(attrs={'class':'form-control'}),
            'department':forms.Select(attrs={'class':'form-select'}),
            'course':forms.Select(attrs={'class':'form-select'}),
            'purpose':forms.Select(attrs={'class':'form-control'}),
            
        }
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).order_by('name')

            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('name')
            

School_Project/School_App/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render,redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from . models import Student, Course
from . forms import StudentForm

# Create your views here.
def home(request):
    
    return render(request,"index.html")



# Create your views here.
def register(request):
    if request.method=='POST':
        uname=request.POST['uname']
        passwd=request.POST['password']
        passwd1=request.POST['cpassword']
        if passwd == passwd1:
            if User.objects.filter(username=uname).exists():
                messages.info(request,"User name already taken!")
                return redirect('School_App:register')
            else:
                user=User.objects.create_user(username=uname,
                                              password=passwd)
                user.save()
                print("User created")
                return redirect('School_App:login')
        else:
            messages.info(request,"Password not matched!")
            return redirect('School_App:register')
        return redirect('/')
    else:
        return render(request,"register.html")

def login(request):
    if request.method == 'POST':
        uname=request.POST['uname']
        passwd=request.POST['password']
        user=auth.authenticate(username=uname,password=passwd)
        if user is not None:
            auth.login(request,user)
            return redirect('School_App:enroll')
        else:
            messages.info(request,"Invalid credentials!")
            return redirect('School_App:login')
    return render(request,"login.html")

def enroll(request):
    return render(request,"enroll.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

class StudentCreateView(SuccessMessageMixin,CreateView):
    model = Student

    form_class = StudentForm
    
    template_name = 'enroll_form.html'
    
    def get_success_url(self):
        return reverse_lazy('School_App:student_add')
    
    success_message = "Enquiry Registered Successfully. Our Team will Contact You Soon..."
    

def load_courses(request):
    department_id = request.GET.get('department')
    courses = Course.objects.filter(department_id=department_id).order_by('name')
    return render(request,'myuser/course_dropdown_list_options.html',{'courses': courses})

School_Project/templates/enroll.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <!--Bootstrap Icons-->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.3/font/bootstrap-icons.min.css">


    <!--Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <title>Admissions Open Now!</title>
</head>
<body class="login-body">
<header class="login-header">

    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand nav-link active" href="{% url 'School_App:home' %}"><img src="{% static 'image/logo/logo_sch.png' %}" width="100px" height="100px" alt="">The Quest
                School</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'School_App:home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                   <li style="color:white;font-size:12px;" class="nav-item">Hello,{{user}}</li>&nbsp;&nbsp;
                   <li><a class="nav-link" style="color:white;font-size:18px;" href="{% url 'School_App:enroll' %}">Enquire</a></li>&nbsp;&nbsp;
                    <li><a class="nav-link" style="color:white;font-size:18px;" href="{% url 'School_App:logout' %}">Logout</a></li>&nbsp;&nbsp;

                   {% else %}
                   <li class="nav-item">
                     <a class="nav-link" href="{% url 'School_App:register' %}">Register</a>
                  </li>
                   <li class="nav-item">
                     <a class="nav-link" href="{% url 'School_App:login' %}">LogIn</a>
                  </li>
                   {% endif %}

                   
                    
                    <li>
                        <div class="navbar-toggler-icon">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </div>
                    </li>

                </ul>
                
            </div>
        </div>
    </nav>
</header>
<section class="enroll-body">
<div class="carousel-item active" style="margin-left:10px;">
                <div class="carousel-container">
                    <div class="carousel-content-container">
                        <h2>Admissions Open for the Upcoming Year.</h2>
                        <p>We believe that choosing the right educational institution is a crucial decision for every
                            parent and student.
                            We understand that you are seeking a school that offers exceptional academic opportunities,
                            and a commitment to holistic development.</p>
                        <div class="buttons">
                            <a href="{% url 'School_App:student_add' %}" class="button1">Get Started !!!</a>

                        </div>
                    </div>
                </div>
</div>
</section>
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>

</body>
</html>

School_Project/templates/enroll_form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>  
<meta charset="utf-8">
<title>Enrollment Form</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <!--Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link href= 
'https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css'
          rel='stylesheet'> 
<style type="text/css">

    .logo{
        
        margin-left: 50%;
    }
    body{
        background-repeat: no-repeat;
        background-size: cover;
        
    }
    form{
        width: 50%;
        height: 100%;
        background: transparent;
        border: 2px solid;
        border-radius: 12px;
        padding: 20px;
        margin-left: 28%;
        font-weight: 1000;
        opacity: .9;
        backdrop-filter: blur(20px);
        box-shadow: 0 0 30px rgba(0,0,0,.5);
        
    }
    .form input:focus~label,
    .form input:valid~label{
    top: -5px;
}
</style>


</head>
<body background="{% static 'image/slider/full_bluegrey.avif' %}">
    <a href="{% url 'School_App:home' %}"><img class="logo" src="{% static 'image/logo/logo_sch.png' %}" width="100px" height="70px" alt=""></a>
    <br>
    <div class="form-group">
        <div style="justify-content:center;text-align:center;color:rgb(1, 43, 5)">
            {% for msg in messages %}
            <h3 class="justify-content-center">{{msg}}</h3>
            Return <a href="{% url 'School_App:home' %}">Home</a> Page.
            {% endfor %}
        </div>
    <form method="post" id="studentForm"  data-courses-url="{% url 'School_App:ajax_load_courses' %}" novalidate>
        
        <h1 style="text-align:center">Enquire!</h1>
        {% csrf_token %}
        
            {{ form.as_p }}
        
        <button class="btn sub" type="submit">Submit</button>
        <a href="{% url 'School_App:student_add' %}"></a>
        <div style="justify-content:center;text-align:center;color:rgb(1, 43, 5)">
            {% for msg in messages %}
            <p class="justify-content-center">{{msg}}</p>
            Return <a href="{% url 'School_App:home' %}">Home</a> Page.
            {% endfor %}
        </div>
    </form>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
      
    <script src= 
"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" > 
    </script> 
      
    <script src= 
"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" > 
    </script>
    <script>
        $("#id_department").change(function () {
            var url = $("#studentForm").attr("data-courses-url");
            var departmentId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'department' : departmentId
                },
                success: function (data) {
                    $("#id_course").html(data);
                }
            });
        });  
        $( function() {
     $( "#datepicker" ).datepicker({
        inline:true
     });
   } );      
    </script>
    
</body>
</html>

School_Project/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
    <!--Bootstrap Icons-->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.3/font/bootstrap-icons.min.css">


    <!--Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <title>Welcome to The Quest School</title>
</head>

<body>
<section>
<header>

    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'School_App:home' %}"><img src="{% static 'image/logo/logo_sch.png' %}"
                                                                           width="100px" height="100px" alt="">The Quest
                School</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'School_App:home' %}">Home&nbsp;</a>
                    </li>
                    {% if user.is_authenticated %}
                   <li style="color:white;font-size:12px;" class="nav-item">Hello,{{user}}</li>&nbsp;&nbsp;
                   <li><a class="nav-link" style="color:white;font-size:18px;" href="{% url 'School_App:enroll' %}">Enquire</a></li>&nbsp;&nbsp;
                    <li><a class="nav-link" style="color:white;font-size:18px;" href="{% url 'School_App:logout' %}">Logout</a></li>&nbsp;&nbsp;

                   {% else %}
                   <li class="nav-item">
                     <a class="nav-link" href="{% url 'School_App:register' %}">Register</a>
                  </li>
                   <li class="nav-item">
                     <a class="nav-link" href="{% url 'School_App:login' %}">LogIn</a>
                  </li>
                   {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Departments
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item"
                                   href="https://en.wikipedia.org/wiki/Mathematics">Mathematics</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Physics">Physics</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Chemistry">Chemistry</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer
                                Science</a></li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Information_technology">Information
                                Technology</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contact</a>
                    </li>
                    

                </ul>
            </div>
        </div>
    </nav>
</header>
<section class="hero" id="hero" >
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="true">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="carousel-background">
                    <img src="{% static 'image/slider/bg_slider_1.jpg' %}" alt="">
                </div>

                <div class="carousel-container">
                    <div class="carousel-content-container">
                        <h2>Welcome to The Quest School</h2>
                        <p>We believe that choosing the right educational institution is a crucial decision for every
                            parent and student.
                            We understand that you are seeking a school that offers exceptional academic opportunities,
                            and a commitment to holistic development.</p>
                        <div class="buttons">
                            <a href="{% url 'School_App:login' %}" class="button1">Know More</a>

                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="carousel-background">
                    <img src="{% static 'image/slider/bg_slider_2.webp' %}" alt="">
                </div>

                <div class="carousel-container">
                    <div class="carousel-content-container">
                        <h2>Beyond Classrooms,</h2>
                        <p>provides Opportunities to Explore their Interests and Develop New Talents.</p>
                        <div class="buttons">
                            <a href="{% url 'School_App:login' %}" class="button1">Admissions</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="false"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>
<section class="about" id="about">
    <br>
    <h2 class="about-h2">About Us</h2>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 d-none d-lg-flex">
                <img src="{% static 'image/about/aboutus.jpeg' %}" width="100%" height="800px" class="img-fluid" alt="">
            </div>
            <div class="col-md-6">
                <div class="about-content">
                    <br>
                    <h2>Welcome to The Quest School</h2>
                    <br>
                    <p>Our students receive a well-rounded education that prepares them for success in the global arena.
                        Whether it's in academics, sports, or extracurricular activities, our students are encouraged to
                        push their boundaries and achieve their goals.</p>
                    <p>The interest of students is given top priority and counseling is taken up to help students identify their interests and careers. Our course structure is comprehensive and scientifically designed for both teachers and students to evaluate progress.</p>
                    <div class="buttons">
                        <a href="{% url 'School_App:home' %}" class="button2">Read More<i class="bi bi-arrow-right-circle-fill"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<br>
<!-- <section>
    <br>
    <h2 class="about-h2">Our Departments</h2>
    <br>
    <div class="row">
        {% for i in course %}
        <div class="col-lg-4 mb-4">
            <div class="card" style="margin-left:5%; width: 22rem; height: 28rem;">
                <img src="{{i.cimg.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{i.cname}}</h5><br>
                    <p class="card-text">{{i.des}}</p>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section> -->
<section id="contact">
    <br>
    <h2 class="about-h2">Contact</h2>
    <br>

      <!-- Content Row -->
      <div class="row">
        <!-- Map Column -->
        <div class="col-lg-8 mb-4">
          <!-- Embedded Google Map -->
            <h4 style="margin-left: 10%;font-family: 'Young Serif', serif;">Our location</h4><br>
          <iframe width="75%" height="300px" frameborder="0" scrolling="no" style="margin-left: 10%;" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d250644.76835099258!2d76.80241722731466!3d11.014261489558132!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba859af2f971cb5%3A0x2fc1c81e183ed282!2sCoimbatore%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1696571487474!5m2!1sen!2sin"></iframe>
        </div>
        <!-- Contact Details Column -->
        <div class="col-lg-4 mb-4 contact-right">
          <h4 style="font-family: 'Young Serif', serif;">Address Details</h4><br>
          <p style="font-family: 'Young Serif', serif;font-size:16px;font-weight:none;">
            3481 Melrose Place
            <br>Palakkad Main Rd, Ettimadai, Tamil Nadu 641105
            <br>
          </p>
          <div class="phone">
              <p>
            <abbr title="Phone">P</abbr>&nbsp;: (123) 456-7890
          </p>
          <p>
            <abbr title="Email">E</abbr>&nbsp;:
            <a href="mailto:quest@tqs.in">quest@tqs.in
            </a>
          </p>
          <p>
            <abbr title="Hours">H</abbr>&nbsp;: Monday - Friday: 9:00 AM to 5:00 PM
          </p>
        </div>
      </div>
      <!-- /.row -->

      <!-- Contact Form -->
      <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->


    </div>
</section>
<footer class="footer">
        <div class="container">
            <div class="footer-logo">
				<a href="{% url 'School_App:home' %}"><img src="{% static 'image/logo/logo_sch.png' %}" width="100px" height="100px" alt=""></a>
			</div>
            <!--foote_bottom_ul_amrc ends here-->
            <p class="copyright text-center">All Rights Reserved. &copy; 2018 <a href="{% url 'School_App:home' %}">The Quest School</a>

            </p>
            <ul class="social_footer_ul">
				<li><a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a></li>
				<li><a href="https://twitter.com/"><i class="fab fa-twitter"></i></a></li>
				<li><a href="https://in.linkedin.com/"><i class="fab fa-linkedin"></i></a></li>
				<li><a href="https://github.com/"><i class="fab fa-github"></i></a></li>
            </ul>
            <!--social_footer_ul ends here-->
        </div>
    </footer>
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </section>
<a class="gotopbtn" href=""><i class="fas fa-arrow-up"></i></a>
</body>

</html>

School_Project/templates/myuser/course_dropdown_list_options.html
<option value="">--------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{  course.name}}</option>
{% endfor %}